export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "black", display: "flex", justifyContent: "center", alignItems:"center"}}>{children}</body>
    </html>
  )
}
